-- Update UploadedFiles table schema for Azure SQL Server
-- Run this script against your Azure SQL database

USE [school-ai-chatbot];
GO

-- Drop old columns if they exist
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'UploadedFiles' AND COLUMN_NAME = 'FilePath')
BEGIN
    ALTER TABLE UploadedFiles DROP COLUMN FilePath;
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'UploadedFiles' AND COLUMN_NAME = 'EmbeddingVector')
BEGIN
    ALTER TABLE UploadedFiles DROP COLUMN EmbeddingVector;
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'UploadedFiles' AND COLUMN_NAME = 'UploadDate')
BEGIN
    ALTER TABLE UploadedFiles DROP COLUMN UploadDate;
END
GO

-- Add new columns if they don't exist
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'UploadedFiles' AND COLUMN_NAME = 'BlobUrl')
BEGIN
    ALTER TABLE UploadedFiles ADD BlobUrl NVARCHAR(500) NULL;
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'UploadedFiles' AND COLUMN_NAME = 'UploadedAt')
BEGIN
    ALTER TABLE UploadedFiles ADD UploadedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE();
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'UploadedFiles' AND COLUMN_NAME = 'Subject')
BEGIN
    ALTER TABLE UploadedFiles ADD Subject NVARCHAR(100) NULL;
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'UploadedFiles' AND COLUMN_NAME = 'Grade')
BEGIN
    ALTER TABLE UploadedFiles ADD Grade NVARCHAR(50) NULL;
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'UploadedFiles' AND COLUMN_NAME = 'Chapter')
BEGIN
    ALTER TABLE UploadedFiles ADD Chapter NVARCHAR(200) NULL;
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'UploadedFiles' AND COLUMN_NAME = 'UploadedBy')
BEGIN
    ALTER TABLE UploadedFiles ADD UploadedBy NVARCHAR(100) NULL;
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'UploadedFiles' AND COLUMN_NAME = 'Status')
BEGIN
    ALTER TABLE UploadedFiles ADD Status NVARCHAR(50) NULL DEFAULT 'Pending';
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'UploadedFiles' AND COLUMN_NAME = 'TotalChunks')
BEGIN
    ALTER TABLE UploadedFiles ADD TotalChunks INT NULL;
END
GO

PRINT 'UploadedFiles table schema updated successfully!';
GO
