// <auto-generated />
using System;
using ImageAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ImageAPI.Migrations
{
    [DbContext(typeof(ImageDbContext))]
    [Migration("20251107232439_AddInventoryImageTable")]
    partial class AddInventoryImageTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ImageAPI.Models.ImageRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("ImageName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("ImageName");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContentType = "image/jpeg",
                            CreatedDate = new DateTime(2025, 11, 7, 23, 24, 36, 765, DateTimeKind.Utc).AddTicks(7158),
                            Description = "A sample image for testing",
                            FileSize = 1024000L,
                            ImageName = "Sample Image 1",
                            ImagePath = "C:\\temp\\sample1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            ContentType = "image/png",
                            CreatedDate = new DateTime(2025, 11, 7, 23, 24, 36, 765, DateTimeKind.Utc).AddTicks(7687),
                            Description = "Another sample image for testing",
                            FileSize = 2048000L,
                            ImageName = "Sample Image 2",
                            ImagePath = "C:\\temp\\sample2.png"
                        });
                });

            modelBuilder.Entity("ImageAPI.Models.InventoryImage", b =>
                {
                    b.Property<string>("ItemNum")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Store_ID")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ImageLocation")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<long?>("ID")
                        .HasColumnType("bigint");

                    b.Property<int?>("Position")
                        .HasColumnType("int");

                    b.HasKey("ItemNum", "Store_ID", "ImageLocation");

                    b.HasIndex("ItemNum");

                    b.HasIndex("Store_ID");

                    b.HasIndex("ItemNum", "Store_ID");

                    b.ToTable("Inventory_Image");

                    b.HasData(
                        new
                        {
                            ItemNum = "ITEM001",
                            Store_ID = "ST001",
                            ImageLocation = "D:\\school-ai-chatbot\\winform_project\\TestImages\\test-red.png",
                            ID = 1L,
                            Position = 1
                        },
                        new
                        {
                            ItemNum = "ITEM001",
                            Store_ID = "ST001",
                            ImageLocation = "D:\\school-ai-chatbot\\winform_project\\TestImages\\test-blue.png",
                            ID = 2L,
                            Position = 2
                        },
                        new
                        {
                            ItemNum = "ITEM002",
                            Store_ID = "ST002",
                            ImageLocation = "D:\\school-ai-chatbot\\winform_project\\TestImages\\test-gradient.jpg",
                            ID = 3L,
                            Position = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
