// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using SchoolAiChatbotBackend.Data;

#nullable disable

namespace SchoolAiChatbotBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251115000000_RemovePineconeVectorId")]
    partial class RemovePineconeVectorId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // Note: This is a simplified version. The full model is preserved in AppDbContextModelSnapshot.cs
#pragma warning restore 612, 618
        }
    }
}
