# Netlify Configuration
[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Redirect rules for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API proxy (if needed)
[[redirects]]
  from = "/api/*"
  to = "https://school-ai-chatbot-app-BACKEND_URL.azurewebsites.net/api/:splat"
  status = 200
  force = true