name: Deploy .NET API to Azure App Service with SQL Database

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # Infrastructure deployment
  deploy-infrastructure:
    runs-on: ubuntu-latest
    outputs:
      app-service-name: ${{ steps.deploy.outputs.appServiceName }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true
    
    - name: Create App Service Plan
      run: |
        az appservice plan create \
          --name school-ai-chatbot-plan \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP_NAME }} \
          --location "East US" \
          --sku FREE
    
    - name: Create App Service
      id: deploy
      run: |
        az webapp create \
          --name school-ai-chatbot-app-${{ github.run_id }} \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP_NAME }} \
          --plan school-ai-chatbot-plan \
          --runtime "DOTNETCORE|6.0"
        
        # Set app settings
        az webapp config appsettings set \
          --name school-ai-chatbot-app-${{ github.run_id }} \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP_NAME }} \
          --settings \
            ASPNETCORE_ENVIRONMENT=Production \
            OpenAI__ApiKey="${{ secrets.OPENAI_API_KEY }}" \
            JWT__SecretKey="${{ secrets.JWT_SECRET_KEY }}" \
            ConnectionStrings__DefaultConnection="InMemory"
        
        echo "appServiceName=school-ai-chatbot-app-${{ github.run_id }}" >> $GITHUB_OUTPUT

  # Application deployment
  build-and-deploy:
    runs-on: ubuntu-latest
    needs: deploy-infrastructure
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
    
    - name: Copy Production Program.cs
      run: cp SchoolAiChatbotBackend/Program.Production.cs SchoolAiChatbotBackend/Program.cs
    
    - name: Restore dependencies
      run: dotnet restore SchoolAiChatbotBackend/SchoolAiChatbotBackend.csproj
    
    - name: Build
      run: dotnet build SchoolAiChatbotBackend/SchoolAiChatbotBackend.csproj --no-restore --configuration Release
    
    - name: Publish
      run: dotnet publish SchoolAiChatbotBackend/SchoolAiChatbotBackend.csproj --no-build --configuration Release --output ./publish
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ needs.deploy-infrastructure.outputs.app-service-name }}
        package: ./publish