name: Deploy .NET API to Azure App Service with SQL Database

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # Infrastructure deployment
  deploy-infrastructure:
    runs-on: ubuntu-latest
    outputs:
      app-service-name: ${{ steps.deploy.outputs.appServiceName }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true
    
    - name: Create App Service and Plan
      id: deploy
      run: |
        # Create unique names for this deployment
        APP_NAME="school-ai-chatbot-app-${{ github.run_id }}"
        PLAN_NAME="school-ai-chatbot-plan-${{ github.run_id }}"
        
        echo "Creating App Service Plan: $PLAN_NAME"
        az appservice plan create \
          --name $PLAN_NAME \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP_NAME }} \
          --location "East US" \
          --sku B1
        
        echo "Creating App Service: $APP_NAME"  
        az webapp create \
          --name $APP_NAME \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP_NAME }} \
          --plan $PLAN_NAME \
          --runtime "DOTNETCORE|6.0"
        
        echo "Setting app configuration..."
        az webapp config appsettings set \
          --name $APP_NAME \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP_NAME }} \
          --settings \
            ASPNETCORE_ENVIRONMENT=Production \
            OpenAI__ApiKey="${{ secrets.OPENAI_API_KEY }}" \
            JWT__SecretKey="${{ secrets.JWT_SECRET_KEY }}" \
            ConnectionStrings__DefaultConnection="InMemory"
        
        echo "appServiceName=$APP_NAME" >> $GITHUB_OUTPUT
        echo "App Service URL: https://$APP_NAME.azurewebsites.net"

  # Application deployment
  build-and-deploy:
    runs-on: ubuntu-latest
    needs: deploy-infrastructure
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
    
    - name: Copy Production Program.cs
      run: cp SchoolAiChatbotBackend/Program.Production.cs SchoolAiChatbotBackend/Program.cs
    
    - name: Restore dependencies
      run: dotnet restore SchoolAiChatbotBackend/SchoolAiChatbotBackend.csproj
    
    - name: Build
      run: dotnet build SchoolAiChatbotBackend/SchoolAiChatbotBackend.csproj --no-restore --configuration Release
    
    - name: Publish
      run: dotnet publish SchoolAiChatbotBackend/SchoolAiChatbotBackend.csproj --no-build --configuration Release --output ./publish
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ needs.deploy-infrastructure.outputs.app-service-name }}
        package: ./publish